#!/usr/bin/env sh
. "$(dirname "$0")/common.sh"


# Initial echo message
echo "Starting pre-push checks..."

# Build
echo "Running build process..."
yarn run build || {
  echo "Build process failed. Ensure all build tasks complete successfully. Address any issues, make the necessary adjustments, and try pushing again."
  exit 1
}

echo "All checks passed successfully. Proceeding with push."
